name: mypy and ruff

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    - name: mypy
      run: |
        mypy       prism/callbacks/ prism/cli/ prism/client/ prism/connectors/ prism/db/ prism/decorators/ prism/engine/ prism/logging/ prism/runtime/ prism/exceptions.py prism/main.py prism/target.py prism/task.py prism/utils.py
        ruff check prism/callbacks/ prism/cli/ prism/client/ prism/connectors/ prism/db/ prism/decorators/ prism/engine/ prism/logging/ prism/runtime/ prism/exceptions.py prism/main.py prism/target.py prism/task.py prism/utils.py
